export const APP_LOAD = 'APP_LOAD';
export const TEAM = 'TEAM';
export const TEAM_REQUEST = 'TEAM_REQUEST';
export const TEAM_REQUEST_SUCCESS = 'TEAM_REQUEST_SUCCESS';
export const TRANSACTIONS = 'TRANSACTIONS';
export const TRANSACTIONS_REQUEST = 'TRANSACTIONS_REQUEST';
export const TRANSACTIONS_REQUEST_SUCCESS = 'TRANSACTIONS_REQUEST_SUCCESS';
